Client/vendor
masaruohashi/supermercado pull request #3
Opened 2017-12-11 00:48 UTC by FelipeFL96

2017-12-11 01:19 UTC, masaruohashi requested changes

2017-12-11 01:19 UTC, masaruohashi commented on WebContent/app/assets/stylesheets/index.css
> +.hidden{
isso tem no [bootstrap](https://getbootstrap.com/docs/3.3/css/#helper-classes-show-hide) e vai dar ruim, pq eu tava usando na pagina de criação de pedido, sendo que aquele `hidden` tem que dar um `display: none`. Para `visibility: hidden` usa o `.invisible` do bootstrap

2017-12-11 01:19 UTC, masaruohashi commented on WebContent/app/views/clients/form.jsp
> +      	    <%Client client = (Client) request.getAttribute("client"); %>
Em vez de fazer esse `if-else` como os 2 layouts são iguais, vc pode passar um objeto client vazio no caso da criação, e dessa forma, não precisaria de código repetido

2017-12-11 01:19 UTC, masaruohashi commented on WebContent/app/views/orders/list.jsp
> +	  <li class="nav-item"><a href="clientes">Cliente</a></li>
Prefira usar espaço em vez de tab para espaçamentos. Tab não tem tamanho fixo, e pode ficar desalinhado se for combinado com espaço.

2017-12-11 01:19 UTC, masaruohashi commented on src/com/supermercado/dao/SellersDAO.java
> +import com.supermercado.models.Client;
Não entendi pq precisa do client aqui. Provavelmente veio do `ctrl+c ctrl+v`

2017-12-11 01:19 UTC, masaruohashi commented on src/com/supermercado/jdbc/ConnectionFactory.java
> +      connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermercado", "root", "960403");
Não commita as alterações nesse arquivo. Ele depende do computador que ta rodando. Por facilidade deixa do jeito que tava antes, e muda no seu pc, sem commitar

2017-12-11 23:48 UTC, FelipeFL96 commented on WebContent/app/assets/stylesheets/index.css
> +.hidden{
Não precisou do .invisible. Só o hidden do bootstrap já foi suficiente pra produzir o efeito que eu precisava. Não lembrei que isso já existia

2017-12-11 23:50 UTC, FelipeFL96 commented on src/com/supermercado/dao/SellersDAO.java
> +import com.supermercado.models.Client;
Sim. Acho que foi adicionado automaticamente quando eu copiei umas funções do cliente

2017-12-12 00:16 UTC, FelipeFL96 commented
Já fiz as alterações. Devo abrir um novo pull request ou esse ainda vale?

2017-12-12 00:32 UTC, masaruohashi commented
Ainda vale

2017-12-12 00:33 UTC, masaruohashi approved these changes

2017-12-12 00:35 UTC, merged