Crud products categories
masaruohashi/supermercado pull request #4
Opened 2017-12-11 21:49 UTC by BrunoSaito

Implementa CRUD para produtos e categorias.

2017-12-11 22:44 UTC, brunonishimoto commented on WebContent/app/views/categories/index.jsp
> +<%@ page import="com.supermercado.dao.CategoriesDAO" %>
Esse import é necessário?

2017-12-11 22:44 UTC, brunonishimoto commented on WebContent/app/views/products/edit.jsp
> +<%@ page import="br.com.supermercado.models.Provider" %>
Aqui seria só `com.supermercado.models.Provider` não?

2017-12-12 00:51 UTC, masaruohashi requested changes

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/categories/edit.jsp
> +            <form action="editar?id=<%=selected_category.getId()%>" method="POST" class="form-group">
Isso não faz sentido. O `POST` por padrão deveria passar parâmetros na requisição, sem usar a url. Se vc quiser fazer algo desse tipo, coloca um campo `hidden` com o `value` igual a isso ae

```html
<input class="hidden" type="text" name="id" value="<%= selected_category.getId() %>" />
```

Além disso, por padrão, o se usa mixed case pra [nome de variáveis em Java](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Java). No caso, deveria ser `selectedCategory`

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/categories/edit.jsp
> +<script>$('#messageModal').modal({show: true})</script>
Por que tem isso aqui?

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/categories/index.jsp
> +    $(document).ready(function() {
Aqui tbm...

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/categories/new.jsp
> +<script>
x3

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/edit.jsp
> +                        <% for(Category category : categories) {
em vez de fazer isso, fica mais claro se vc fechar a tag do Java na linha, e abrir outra pra fechar o `}`

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/edit.jsp
> +                        <% }
Aqui ficaria mais claro se as duas coisas estivessem na mesma linha

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/edit.jsp
> +<script>
x4

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/index.jsp
> +<script>
x5

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/new.jsp
> +        <li class="nav-item"><a href="#">Pedido</a></li>
coloca a referencia nas paginas

2017-12-12 00:51 UTC, masaruohashi commented on WebContent/app/views/products/new.jsp
> +<script>
x6

2017-12-13 01:40 UTC, masaruohashi approved these changes

2017-12-13 01:40 UTC, merged